In [2]:
import pandas as pd

In [3]:
fruits = pd.Series(
    ["Apple", "Banana", "Mango", "Orange", "Grapes",
     "Pineapple", "Guava", "Papaya", "Kiwi", "Watermelon"],
    index=["f1", "f2", "f3", "f4", "f5", "f6", "f7", "f8", "f9", "f10"]
)
print(fruits)

f1          Apple
f2         Banana
f3          Mango
f4         Orange
f5         Grapes
f6      Pineapple
f7          Guava
f8         Papaya
f9           Kiwi
f10    Watermelon
dtype: object

In [4]:
sales = {
    "Sales Person Name": ["Arin", "Vyom", None, "Ishani", "Reyansh",
                          "Tvesha", "Aarav", "Diya", "Kabir", "Meera",
                          "Rohan", "Anaya", None, "Nihar", "Saanvi"],
    "City": ["Bhubaneswar", None, "Cuttack", "Raurkela", None,
             "Talcher", "Puri", "Sambalpur", "Balasore", "Berhampur",
             "Jharsuguda", None, "Baripada", "Bhadrak", "Angul"],
    "Store": ["D Mart", "V Mart", None, "Reliance", "Jio Mart",
              None, "Big Bazaar", "Smart Point", "Metro Mart", "Easy Day",
              "Reliance Fresh", "D Mart", None, "More", "V Mart"],
    "Unit Sold": [84, None, 132, 97, None,
                  118, 145, 110, 98, 76,
                  125, 90, None, 160, 105],
    "Total Sale": [42800, 39500, None, 51200, 
                   None,47650, 69000, 53000, 48000, 37000,
                   61000, None, 45500, 72000, 50500],
    "Commission Amount": [2140, None, 3960, None, 2860,
                          2382, 3450, 2650, 2400, 1850,
                          3050, 2250, None, 3600, 2525]
}
df = pd.DataFrame(sales)
print(df)

   Sales Person Name         City           Store  Unit Sold  Total Sale  \
0               Arin  Bhubaneswar          D Mart       84.0     42800.0
1               Vyom         None          V Mart        NaN     39500.0
2               None      Cuttack            None      132.0         NaN
3             Ishani     Raurkela        Reliance       97.0     51200.0
4            Reyansh         None        Jio Mart        NaN         NaN
5             Tvesha      Talcher            None      118.0     47650.0
6              Aarav         Puri      Big Bazaar      145.0     69000.0
7               Diya    Sambalpur     Smart Point      110.0     53000.0
8              Kabir     Balasore      Metro Mart       98.0     48000.0
9              Meera    Berhampur        Easy Day       76.0     37000.0
10             Rohan   Jharsuguda  Reliance Fresh      125.0     61000.0
11             Anaya         None          D Mart       90.0         NaN
12              None     Baripada            None        NaN     45500.0
13             Nihar      Bhadrak            More      160.0     72000.0
14            Saanvi        Angul          V Mart      105.0     50500.0

    Commission Amount
0              2140.0
1                 NaN
2              3960.0
3                 NaN
4              2860.0
5              2382.0
6              3450.0
7              2650.0
8              2400.0
9              1850.0
10             3050.0
11             2250.0
12                NaN
13             3600.0
14             2525.0

In [5]:
df.head()

,Sales Person Name,City,Store,Unit Sold,Total Sale,Commission Amount
0,Arin,Bhubaneswar,D Mart,84.0,42800.0,2140.0
1,Vyom,None,V Mart,NaN,39500.0,NaN
2,None,Cuttack,None,132.0,NaN,3960.0
3,Ishani,Raurkela,Reliance,97.0,51200.0,NaN
4,Reyansh,None,Jio Mart,NaN,NaN,2860.0

In [6]:
df.tail()

,Sales Person Name,City,Store,Unit Sold,Total Sale,Commission Amount
10,Rohan,Jharsuguda,Reliance Fresh,125.0,61000.0,3050.0
11,Anaya,None,D Mart,90.0,NaN,2250.0
12,None,Baripada,None,NaN,45500.0,NaN
13,Nihar,Bhadrak,More,160.0,72000.0,3600.0
14,Saanvi,Angul,V Mart,105.0,50500.0,2525.0

In [8]:
df.shape

(15, 6)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sales Person Name  13 non-null     object
 1   City               12 non-null     object
 2   Store              12 non-null     object
 3   Unit Sold          12 non-null     float64
 4   Total Sale         12 non-null     float64
 5   Commission Amount  12 non-null     float64
dtypes: float64(3), object(3)
memory usage: 852.0+ bytes

In [10]:
df.describe()

        Unit Sold    Total Sale  Commission Amount
count   12.000000     12.000000           12.00000
mean   111.666667  51429.166667         2759.75000
std     25.288637  10925.542598          641.60369
min     76.000000  37000.000000         1850.00000
25%     95.250000  44825.000000         2349.00000
50%    107.500000  49250.000000         2587.50000
75%    126.750000  55000.000000         3150.00000
max    160.000000  72000.000000         3960.00000

In [12]:
df.dtypes

Sales Person Name     object
City                  object
Store                 object
Unit Sold            float64
Total Sale           float64
Commission Amount    float64
dtype: object

In [14]:
df.columns

Index(['Sales Person Name', 'City', 'Store', 'Unit Sold', 'Total Sale',
       'Commission Amount'],
      dtype='object')

In [15]:
df.index

RangeIndex(start=0, stop=15, step=1)

In [16]:
df.isnull().sum()

Sales Person Name    2
City                 3
Store                3
Unit Sold            3
Total Sale           3
Commission Amount    3
dtype: int64

In [17]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
dtype: bool

In [18]:
df.duplicated().sum()

np.int64(0)

In [20]:
df.nunique()

Sales Person Name    13
City                 12
Store                10
Unit Sold            12
Total Sale           12
Commission Amount    12
dtype: int64

In [22]:
df.value_counts()

Sales Person Name  City         Store           Unit Sold  Total Sale  Commission Amount
Aarav              Puri         Big Bazaar      145.0      69000.0     3450.0               1
Arin               Bhubaneswar  D Mart          84.0       42800.0     2140.0               1
Diya               Sambalpur    Smart Point     110.0      53000.0     2650.0               1
Kabir              Balasore     Metro Mart      98.0       48000.0     2400.0               1
Meera              Berhampur    Easy Day        76.0       37000.0     1850.0               1
Nihar              Bhadrak      More            160.0      72000.0     3600.0               1
Rohan              Jharsuguda   Reliance Fresh  125.0      61000.0     3050.0               1
Saanvi             Angul        V Mart          105.0      50500.0     2525.0               1
Name: count, dtype: int64

In [24]:
df.columns.tolist()

['Sales Person Name',
 'City',
 'Store',
 'Unit Sold',
 'Total Sale',
 'Commission Amount']

In [25]:
df.index.tolist()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [26]:
df.empty

False

In [29]:
df.sample(8)

,Sales Person Name,City,Store,Unit Sold,Total Sale,Commission Amount
11,Anaya,None,D Mart,90.0,NaN,2250.0
12,None,Baripada,None,NaN,45500.0,NaN
5,Tvesha,Talcher,None,118.0,47650.0,2382.0
9,Meera,Berhampur,Easy Day,76.0,37000.0,1850.0
6,Aarav,Puri,Big Bazaar,145.0,69000.0,3450.0
13,Nihar,Bhadrak,More,160.0,72000.0,3600.0
0,Arin,Bhubaneswar,D Mart,84.0,42800.0,2140.0
10,Rohan,Jharsuguda,Reliance Fresh,125.0,61000.0,3050.0