In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("finance_loan_portfolio_python_dataset.csv")

In [4]:
df.head() #to view the first 5 rows of the dataframe

,Record_ID,Customer_ID,Customer_Name,Age,Gender,City,Employment_Type,Annual_Income_INR,Credit_Score,Loan_Type,...,Late_Payment_Count,Default_Flag,Debt_to_Income_Ratio,Savings_Balance_INR,Investment_Value_INR,Risk_Category,Last_Payment_Date,Payment_Mode,Acquisition_Channel,Branch_Name
0,FIN-00255,CUST-00839,Arjun Gupta,64.0,Female,Jaipur,Self-Employed,679000.0,707.0,Home Loan,...,7,Yes,0.920,42160.72,78362.21,High,2026-05-30,Auto-Debit,Partner,Nagpur Civil Lines
1,FIN-00474,CUST-00508,Rohan Iyer,63.0,Male,Mumbai,Salaried,1275000.0,745.0,Personal Loan,...,0,No,0.386,167007.37,435254.86,Low,2026-07-10,Net Banking,Website,Chennai T Nagar
2,FIN-00725,CUST-00013,Rohan Jadhav,48.0,Female,Lucknow,Government Employee,1390000.0,663.0,Personal Loan,...,2,No,NaN,6378.50,0.00,Low,NaN,UPI,Branch,Nashik Road
3,FIN-00438,CUST-00328,Tanvi Chaudhary,56.0,Male,Nashik,Government Employee,719000.0,695.0,Vehicle Loan,...,1,No,0.689,353397.61,148295.33,Medium,2026-06-24,Auto-Debit,Website,Delhi Connaught Place
4,FIN-00661,CUST-00740,Rahul Iyer,53.0,Female,Nashik,Business Owner,7218000.0,665.0,Home Loan,...,3,No,0.075,1210618.96,1460036.03,Medium,2026-04-24,UPI,Branch,Jaipur C Scheme

In [5]:
df.info() # to check for the column infracstructure, non-null count, datatype of coloumn

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1230 entries, 0 to 1229
Data columns (total 28 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Record_ID                1230 non-null   object
 1   Customer_ID              1230 non-null   object
 2   Customer_Name            1230 non-null   object
 3   Age                      1202 non-null   float64
 4   Gender                   1208 non-null   object
 5   City                     1198 non-null   object
 6   Employment_Type          1205 non-null   object
 7   Annual_Income_INR        1196 non-null   float64
 8   Credit_Score             1188 non-null   float64
 9   Loan_Type                1230 non-null   object
 10  Loan_Amount_INR          1230 non-null   int64
 11  Interest_Rate_Pct        1212 non-null   float64
 12  Loan_Term_Months         1230 non-null   int64
 13  Monthly_EMI_INR          1230 non-null   float64
 14  Disbursement_Date        1230 non-null   object
 15  Outstanding_Balance_INR  1206 non-null   float64
 16  Payment_Status           1230 non-null   object
 17  Days_Past_Due            1230 non-null   int64
 18  Late_Payment_Count       1230 non-null   int64
 19  Default_Flag             1230 non-null   object
 20  Debt_to_Income_Ratio     1195 non-null   float64
 21  Savings_Balance_INR      1199 non-null   float64
 22  Investment_Value_INR     1198 non-null   float64
 23  Risk_Category            1230 non-null   object
 24  Last_Payment_Date        1203 non-null   object
 25  Payment_Mode             1210 non-null   object
 26  Acquisition_Channel      1230 non-null   object
 27  Branch_Name              1230 non-null   object
dtypes: float64(9), int64(4), object(15)
memory usage: 269.2+ KB

In [7]:
df.shape

(1230, 28)

In [9]:
df.describe() #to get the basic stastistical summary for numerical only

,Age,Annual_Income_INR,Credit_Score,Loan_Amount_INR,Interest_Rate_Pct,Loan_Term_Months,Monthly_EMI_INR,Outstanding_Balance_INR,Days_Past_Due,Late_Payment_Count,Debt_to_Income_Ratio,Savings_Balance_INR,Investment_Value_INR
count,1202.000000,1.196000e+03,1188.000000,1.230000e+03,1212.000000,1230.000000,1230.000000,1.206000e+03,1230.000000,1230.000000,1195.000000,1.199000e+03,1.198000e+03
mean,42.964226,1.386089e+06,684.171717,1.674126e+06,13.708251,70.048780,41653.180146,1.034594e+06,27.930894,2.666667,0.530249,2.852790e+05,2.484833e+05
std,12.896096,1.028175e+06,74.048875,1.861600e+06,4.011314,66.095999,43479.570285,1.720638e+06,48.114059,2.696973,0.265499,3.354904e+05,3.662194e+05
min,21.000000,2.940000e+05,474.000000,4.500000e+04,7.200000,6.000000,1845.090000,0.000000e+00,0.000000,0.000000,0.050000,0.000000e+00,0.000000e+00
25%,32.000000,7.382500e+05,634.000000,4.600000e+05,10.630000,24.000000,15239.642500,0.000000e+00,0.000000,0.000000,0.299000,5.866674e+04,1.853671e+04
50%,43.000000,1.134500e+06,685.000000,9.750000e+05,13.015000,48.000000,29093.575000,3.322209e+05,0.000000,2.000000,0.494000,1.785311e+05,1.314216e+05
75%,54.000000,1.647500e+06,733.000000,2.201250e+06,16.560000,84.000000,53039.820000,1.249156e+06,44.000000,4.000000,0.780000,3.909735e+05,3.178733e+05
max,65.000000,7.292000e+06,850.000000,1.127000e+07,24.000000,300.000000,472335.630000,1.047749e+07,180.000000,13.000000,0.920000,3.202587e+06,3.942651e+06

In [12]:
df.describe(include="all")

,Record_ID,Customer_ID,Customer_Name,Age,Gender,City,Employment_Type,Annual_Income_INR,Credit_Score,Loan_Type,...,Late_Payment_Count,Default_Flag,Debt_to_Income_Ratio,Savings_Balance_INR,Investment_Value_INR,Risk_Category,Last_Payment_Date,Payment_Mode,Acquisition_Channel,Branch_Name
count,1230,1230,1230,1202.000000,1208,1198,1205,1.196000e+03,1188.000000,1230,...,1230.000000,1230,1195.000000,1.199000e+03,1.198000e+03,1230,1203,1210,1230,1230
unique,1200,653,602,NaN,3,15,5,NaN,NaN,6,...,NaN,2,NaN,NaN,NaN,3,406,5,5,10
top,FIN-00977,CUST-00421,Kabir Verma,NaN,Male,Mumbai,Salaried,NaN,NaN,Personal Loan,...,NaN,No,NaN,NaN,NaN,Medium,2026-07-01,Auto-Debit,Mobile App,Nagpur Civil Lines
freq,2,6,8,NaN,596,221,552,NaN,NaN,362,...,NaN,1009,NaN,NaN,NaN,514,28,469,382,134
mean,NaN,NaN,NaN,42.964226,NaN,NaN,NaN,1.386089e+06,684.171717,NaN,...,2.666667,NaN,0.530249,2.852790e+05,2.484833e+05,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,12.896096,NaN,NaN,NaN,1.028175e+06,74.048875,NaN,...,2.696973,NaN,0.265499,3.354904e+05,3.662194e+05,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,21.000000,NaN,NaN,NaN,2.940000e+05,474.000000,NaN,...,0.000000,NaN,0.050000,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,32.000000,NaN,NaN,NaN,7.382500e+05,634.000000,NaN,...,0.000000,NaN,0.299000,5.866674e+04,1.853671e+04,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,43.000000,NaN,NaN,NaN,1.134500e+06,685.000000,NaN,...,2.000000,NaN,0.494000,1.785311e+05,1.314216e+05,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,54.000000,NaN,NaN,NaN,1.647500e+06,733.000000,NaN,...,4.000000,NaN,0.780000,3.909735e+05,3.178733e+05,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,65.000000,NaN,NaN,NaN,7.292000e+06,850.000000,NaN,...,13.000000,NaN,0.920000,3.202587e+06,3.942651e+06,NaN,NaN,NaN,NaN,NaN

DATA CLEANING ----------

1. check for missing value
2. handling the missing value
3. check for duplicate record
4. remove the duplicate records if present

In [15]:
df.isnull().sum() #isnull checks the missing value and sum() is used for number of these

Record_ID                   0
Customer_ID                 0
Customer_Name               0
Age                        28
Gender                     22
City                       32
Employment_Type            25
Annual_Income_INR          34
Credit_Score               42
Loan_Type                   0
Loan_Amount_INR             0
Interest_Rate_Pct          18
Loan_Term_Months            0
Monthly_EMI_INR             0
Disbursement_Date           0
Outstanding_Balance_INR    24
Payment_Status              0
Days_Past_Due               0
Late_Payment_Count          0
Default_Flag                0
Debt_to_Income_Ratio       35
Savings_Balance_INR        31
Investment_Value_INR       32
Risk_Category               0
Last_Payment_Date          27
Payment_Mode               20
Acquisition_Channel         0
Branch_Name                 0
dtype: int64

In [17]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [18]:
df["Annual_Income_INR"] = df["Annual_Income_INR"].fillna(df["Annual_Income_INR"].mean())

In [20]:
df["Gender"] = df["Gender"].fillna("Unknown Gender")

In [21]:
df["City"] = df["City"].fillna("Unknown City")

In [22]:
df["Employment_Type"] = df["Employment_Type"].fillna("Unknown Employment_Type")

In [23]:
df["Credit_Score"] = df["Credit_Score"].fillna(df["Credit_Score"].mean())

In [24]:
df["Interest_Rate_Pct"] = df["Interest_Rate_Pct"].fillna(df["Interest_Rate_Pct"].mean())

In [34]:
df["Outstanding_Balance_INR"] = df["Outstanding_Balance_INR"].fillna(df["Outstanding_Balance_INR"].mean())

In [28]:
df["Debt_to_Income_Ratio"] = df["Debt_to_Income_Ratio"].fillna(df["Debt_to_Income_Ratio"].mean())

In [30]:
df["Savings_Balance_INR"] = df["Savings_Balance_INR"].fillna(df["Savings_Balance_INR"].mean())

In [31]:
df["Investment_Value_INR"] = df["Investment_Value_INR"].fillna(df["Investment_Value_INR"].mean())

In [32]:
df["Last_Payment_Date"] = df["Last_Payment_Date"].fillna("Unknown Last_Payment_Date")

In [33]:
df["Payment_Mode"] = df["Payment_Mode"].fillna("Unknown Payment_Mode")

In [36]:
df.isnull().sum()

Record_ID                  0
Customer_ID                0
Customer_Name              0
Age                        0
Gender                     0
City                       0
Employment_Type            0
Annual_Income_INR          0
Credit_Score               0
Loan_Type                  0
Loan_Amount_INR            0
Interest_Rate_Pct          0
Loan_Term_Months           0
Monthly_EMI_INR            0
Disbursement_Date          0
Outstanding_Balance_INR    0
Payment_Status             0
Days_Past_Due              0
Late_Payment_Count         0
Default_Flag               0
Debt_to_Income_Ratio       0
Savings_Balance_INR        0
Investment_Value_INR       0
Risk_Category              0
Last_Payment_Date          0
Payment_Mode               0
Acquisition_Channel        0
Branch_Name                0
dtype: int64

In [35]:
df.duplicated().sum()

np.int64(30)

In [37]:
df = df.drop_duplicates()

In [42]:
df.shape

(1200, 28)

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1200 entries, 0 to 1229
Data columns (total 28 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Record_ID                1200 non-null   object
 1   Customer_ID              1200 non-null   object
 2   Customer_Name            1200 non-null   object
 3   Age                      1200 non-null   float64
 4   Gender                   1200 non-null   object
 5   City                     1200 non-null   object
 6   Employment_Type          1200 non-null   object
 7   Annual_Income_INR        1200 non-null   float64
 8   Credit_Score             1200 non-null   float64
 9   Loan_Type                1200 non-null   object
 10  Loan_Amount_INR          1200 non-null   int64
 11  Interest_Rate_Pct        1200 non-null   float64
 12  Loan_Term_Months         1200 non-null   int64
 13  Monthly_EMI_INR          1200 non-null   float64
 14  Disbursement_Date        1200 non-null   object
 15  Outstanding_Balance_INR  1200 non-null   float64
 16  Payment_Status           1200 non-null   object
 17  Days_Past_Due            1200 non-null   int64
 18  Late_Payment_Count       1200 non-null   int64
 19  Default_Flag             1200 non-null   object
 20  Debt_to_Income_Ratio     1200 non-null   float64
 21  Savings_Balance_INR      1200 non-null   float64
 22  Investment_Value_INR     1200 non-null   float64
 23  Risk_Category            1200 non-null   object
 24  Last_Payment_Date        1200 non-null   object
 25  Payment_Mode             1200 non-null   object
 26  Acquisition_Channel      1200 non-null   object
 27  Branch_Name              1200 non-null   object
dtypes: float64(9), int64(4), object(15)
memory usage: 271.9+ KB

In [39]:
#unique values in each object coloumn
df['Gender'].unique()

array(['Female', 'Male', 'Non-Binary', 'Unknown Gender'], dtype=object)

In [40]:
df['Gender'].nunique()

4

In [41]:
df['Gender'].value_counts()

Gender
Male              584
Female            565
Non-Binary         29
Unknown Gender     22
Name: count, dtype: int64

In [50]:
df['City'].unique()

array(['Jaipur', 'Mumbai', 'Lucknow', 'Nashik', 'Chennai', 'Delhi',
       'Indore', 'Ahmedabad', 'Bengaluru', 'Unknown City', 'Hyderabad',
       'Pune', 'Thane', 'Surat', 'Kolkata', 'Nagpur'], dtype=object)

In [48]:
df['City'].nunique()

16

In [49]:
df['City'].value_counts()

City
Mumbai          217
Pune            166
Bengaluru        85
Delhi            81
Thane            74
Hyderabad        69
Nashik           62
Nagpur           62
Chennai          59
Surat            53
Jaipur           50
Lucknow          49
Kolkata          49
Indore           47
Ahmedabad        46
Unknown City     31
Name: count, dtype: int64

In [51]:
df['Employment_Type'].unique()

array(['Self-Employed', 'Salaried', 'Government Employee',
       'Business Owner', 'Freelancer', 'Unknown Employment_Type'],
      dtype=object)

In [52]:
df['Employment_Type'].nunique()

6

In [53]:
df['Employment_Type'].value_counts()

Employment_Type
Salaried                   538
Self-Employed              208
Business Owner             168
Freelancer                 145
Government Employee        116
Unknown Employment_Type     25
Name: count, dtype: int64

In [54]:
df['Loan_Type'].unique()

array(['Home Loan', 'Personal Loan', 'Vehicle Loan', 'Gold Loan',
       'Education Loan', 'Business Loan'], dtype=object)

In [55]:
df['Loan_Type'].nunique()

6

In [56]:
df['Loan_Type'].value_counts()

Loan_Type
Personal Loan     356
Vehicle Loan      242
Home Loan         204
Business Loan     167
Education Loan    120
Gold Loan         111
Name: count, dtype: int64

In [62]:
df['Risk_Category'].unique()

array(['High', 'Low', 'Medium'], dtype=object)

In [63]:
df['Risk_Category'].nunique()

3

In [64]:
df['Risk_Category'].value_counts()

Risk_Category
Medium    504
Low       494
High      202
Name: count, dtype: int64

In [65]:
#groupby() - used in order to group the date based on aggregate function - (mean,max,min,count)

In [67]:
df.groupby("Gender")["Annual_Income_INR"].max()

Gender
Female            7218000.0
Male              7292000.0
Non-Binary        4404000.0
Unknown Gender    3652000.0
Name: Annual_Income_INR, dtype: float64

In [70]:
df.groupby("Loan_Type")["Loan_Amount_INR"].sum()

Loan_Type
Business Loan     338690000
Education Loan    169825000
Gold Loan          53425000
Home Loan         937635000
Personal Loan     187300000
Vehicle Loan      323160000
Name: Loan_Amount_INR, dtype: int64

In [71]:
df.groupby(["Loan_Type","Risk_Category"])["Loan_Amount_INR"].sum()

Loan_Type       Risk_Category
Business Loan   High              87005000
                Low               48055000
                Medium           203630000
Education Loan  High              58830000
                Low               57480000
                Medium            53515000
Gold Loan       High               1240000
                Low               18480000
                Medium            33705000
Home Loan       High             383155000
                Low              144405000
                Medium           410075000
Personal Loan   High              26700000
                Low               82290000
                Medium            78310000
Vehicle Loan    High              71910000
                Low              106720000
                Medium           144530000
Name: Loan_Amount_INR, dtype: int64

In [72]:
df.groupby(["Loan_Type","Risk_Category"])["Loan_Amount_INR"].sum().sort_values(ascending=False)

Loan_Type       Risk_Category
Home Loan       Medium           410075000
                High             383155000
Business Loan   Medium           203630000
Vehicle Loan    Medium           144530000
Home Loan       Low              144405000
Vehicle Loan    Low              106720000
Business Loan   High              87005000
Personal Loan   Low               82290000
                Medium            78310000
Vehicle Loan    High              71910000
Education Loan  High              58830000
                Low               57480000
                Medium            53515000
Business Loan   Low               48055000
Gold Loan       Medium            33705000
Personal Loan   High              26700000
Gold Loan       Low               18480000
                High               1240000
Name: Loan_Amount_INR, dtype: int64

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1200 entries, 0 to 1229
Data columns (total 28 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Record_ID                1200 non-null   object
 1   Customer_ID              1200 non-null   object
 2   Customer_Name            1200 non-null   object
 3   Age                      1200 non-null   float64
 4   Gender                   1200 non-null   object
 5   City                     1200 non-null   object
 6   Employment_Type          1200 non-null   object
 7   Annual_Income_INR        1200 non-null   float64
 8   Credit_Score             1200 non-null   float64
 9   Loan_Type                1200 non-null   object
 10  Loan_Amount_INR          1200 non-null   int64
 11  Interest_Rate_Pct        1200 non-null   float64
 12  Loan_Term_Months         1200 non-null   int64
 13  Monthly_EMI_INR          1200 non-null   float64
 14  Disbursement_Date        1200 non-null   object
 15  Outstanding_Balance_INR  1200 non-null   float64
 16  Payment_Status           1200 non-null   object
 17  Days_Past_Due            1200 non-null   int64
 18  Late_Payment_Count       1200 non-null   int64
 19  Default_Flag             1200 non-null   object
 20  Debt_to_Income_Ratio     1200 non-null   float64
 21  Savings_Balance_INR      1200 non-null   float64
 22  Investment_Value_INR     1200 non-null   float64
 23  Risk_Category            1200 non-null   object
 24  Last_Payment_Date        1200 non-null   object
 25  Payment_Mode             1200 non-null   object
 26  Acquisition_Channel      1200 non-null   object
 27  Branch_Name              1200 non-null   object
dtypes: float64(9), int64(4), object(15)
memory usage: 271.9+ KB

QUESTIONS

1. How many total loan records are present in the cleaned dataset?

In [77]:
len(df)

1200

2. How many unique customers are present in the dataset?

In [78]:
df["Customer_ID"].nunique()

653

3. How many customers have more than one loan record?

In [81]:
(df.groupby("Customer_ID").size() > 1).sum()

np.int64(351)

4. What are the unique loan types available in the dataset?

In [82]:
df["Loan_Type"].unique()

array(['Home Loan', 'Personal Loan', 'Vehicle Loan', 'Gold Loan',
       'Education Loan', 'Business Loan'], dtype=object)

5. How many unique cities, branches and employment categories are represented?

In [90]:
print("Cities:", df["City"].nunique())
print("Branches:", df["Branch_Name"].nunique())
print("Employment Categories:", df["Employment_Type"].nunique())

Cities: 16
Branches: 10
Employment Categories: 6

6. How many loan records belong to each loan type?

In [92]:
df["Loan_Type"].value_counts()

Loan_Type
Personal Loan     356
Vehicle Loan      242
Home Loan         204
Business Loan     167
Education Loan    120
Gold Loan         111
Name: count, dtype: int64

7. What percentage of the total loan records belongs to each loan type?

In [93]:
df["Loan_Type"].value_counts(normalize=True)*100

Loan_Type
Personal Loan     29.666667
Vehicle Loan      20.166667
Home Loan         17.000000
Business Loan     13.916667
Education Loan    10.000000
Gold Loan          9.250000
Name: proportion, dtype: float64

8. Which loan type has the highest and lowest number of loan records?

In [98]:
count = df["Loan_Type"].value_counts()
print("Highest:",count.idxmax())
print("Lowest:",count.idxmin())

Highest: Personal Loan
Lowest: Gold Loan

9. How many loan accounts fall under each payment-status category?

In [103]:
df["Payment_Status"].value_counts()

Payment_Status
On Time    389
Closed     385
Late       229
Missed     197
Name: count, dtype: int64

10. What percentage of accounts are on time, late, missed or closed?

In [104]:
df["Payment_Status"].value_counts(normalize=True)*100

Payment_Status
On Time    32.416667
Closed     32.083333
Late       19.083333
Missed     16.416667
Name: proportion, dtype: float64

11. How many accounts fall under each risk category?

In [107]:
df["Risk_Category"].value_counts()

Risk_Category
Medium    504
Low       494
High      202
Name: count, dtype: int64

12. What percentage of loan accounts are marked as defaulted?

In [109]:
df["Default_Flag"].value_counts(normalize=True)*100

Default_Flag
No     82.25
Yes    17.75
Name: proportion, dtype: float64

13. Which five cities have the highest number of loan accounts?

In [115]:
df["City"].value_counts().head()

City
Mumbai       217
Pune         166
Bengaluru     85
Delhi         81
Thane         74
Name: count, dtype: int64

14. How many unique customers are present in each city?

In [120]:
df.groupby("City")["Customer_ID"].nunique()

City
Ahmedabad        46
Bengaluru        81
Chennai          57
Delhi            78
Hyderabad        69
Indore           45
Jaipur           48
Kolkata          47
Lucknow          47
Mumbai          189
Nagpur           60
Nashik           57
Pune            152
Surat            51
Thane            71
Unknown City     30
Name: Customer_ID, dtype: int64

15. Which employment type has the highest number of borrowers?

In [122]:
df["Employment_Type"].value_counts().idxmax()

'Salaried'

16. Which payment mode is used most frequently?

In [124]:
df["Payment_Mode"].value_counts().idxmax()

'Auto-Debit'

17. Which acquisition channel generates the highest number of loan records?

In [127]:
df["Acquisition_Channel"].value_counts().idxmax()

'Mobile App'

18. Which five branches handle the highest number of loan accounts?

In [131]:
df["Branch_Name"].value_counts().head()

Branch_Name
Nagpur Civil Lines       134
Nashik Road              130
Pune Central             129
Bengaluru MG Road        122
Ahmedabad Navrangpura    120
Name: count, dtype: int64

19. What is the total sanctioned loan amount for each loan type?

In [133]:
df.groupby("Loan_Type")["Loan_Amount_INR"].sum()

Loan_Type
Business Loan     338690000
Education Loan    169825000
Gold Loan          53425000
Home Loan         937635000
Personal Loan     187300000
Vehicle Loan      323160000
Name: Loan_Amount_INR, dtype: int64

20. Which loan type has the highest total sanctioned loan amount?

In [134]:
(df.groupby("Loan_Type")["Loan_Amount_INR"].sum()).idxmax()

'Home Loan'

21. What are the average and median loan amounts for each loan type?

In [135]:
df.groupby("Loan_Type")["Loan_Amount_INR"].agg(["mean","median"])

                        mean     median
Loan_Type
Business Loan   2.028084e+06  1830000.0
Education Loan  1.415208e+06  1332500.0
Gold Loan       4.813063e+05   385000.0
Home Loan       4.596250e+06  4235000.0
Personal Loan   5.261236e+05   460000.0
Vehicle Loan    1.335372e+06  1210000.0

22. What are the minimum and maximum loan amounts for each loan type?

In [136]:
df.groupby("Loan_Type")["Loan_Amount_INR"].agg(["min","max"])

                   min       max
Loan_Type
Business Loan   250000   5400000
Education Loan  140000   3735000
Gold Loan        45000   1420000
Home Loan       920000  11270000
Personal Loan    65000   1430000
Vehicle Loan    185000   3120000

23. What is the average interest rate for each loan type?

In [138]:
df.groupby("Loan_Type")["Interest_Rate_Pct"].mean()

Loan_Type
Business Loan     16.910487
Education Loan    11.779373
Gold Loan         13.607700
Home Loan          9.546699
Personal Loan     16.656390
Vehicle Loan      11.806721
Name: Interest_Rate_Pct, dtype: float64

24. Which loan type has the highest average monthly EMI?

In [139]:
(df.groupby("Loan_Type")["Monthly_EMI_INR"].mean()).idxmax()

'Business Loan'

25. What is the total outstanding balance for each loan type?

In [140]:
df.groupby("Loan_Type")["Outstanding_Balance_INR"].sum()

Loan_Type
Business Loan     1.273775e+08
Education Loan    1.101274e+08
Gold Loan         1.101567e+07
Home Loan         7.706345e+08
Personal Loan     7.278132e+07
Vehicle Loan      1.500851e+08
Name: Outstanding_Balance_INR, dtype: float64

26. Which payment-status category has the highest total outstanding balance?

In [141]:
(df.groupby("Payment_Status")["Outstanding_Balance_INR"].mean()).idxmax()

'Missed'

27. What is the average outstanding balance for on-time, late, missed and closed
accounts?

In [144]:
df.groupby("Payment_Status")["Outstanding_Balance_INR"].mean()

Payment_Status
Closed     1.343629e+04
Late       1.773335e+06
Missed     2.231018e+06
On Time    1.005769e+06
Name: Outstanding_Balance_INR, dtype: float64

28. What is the average credit score for each loan type?

In [145]:
df.groupby("Loan_Type")["Credit_Score"].mean()

Loan_Type
Business Loan     681.172806
Education Loan    680.746212
Gold Loan         674.426517
Home Loan         682.446227
Personal Loan     684.050732
Vehicle Loan      692.338968
Name: Credit_Score, dtype: float64

29. What is the average credit score for each employment category?

In [146]:
df.groupby("Employment_Type")["Credit_Score"].mean()

Employment_Type
Business Owner             691.160895
Freelancer                 662.269175
Government Employee        700.791884
Salaried                   689.014720
Self-Employed              672.268551
Unknown Employment_Type    665.446869
Name: Credit_Score, dtype: float64

30. What are the average and median annual incomes for each employment category?

In [149]:
df.groupby("Employment_Type")["Annual_Income_INR"].agg(["mean","median"])

                                 mean        median
Employment_Type
Business Owner           2.984251e+06  2.640500e+06
Freelancer               9.110445e+05  8.820000e+05
Government Employee      1.039967e+06  1.000000e+06
Salaried                 1.083893e+06  1.007000e+06
Self-Employed            1.443450e+06  1.386089e+06
Unknown Employment_Type  1.309371e+06  1.237000e+06

31. What is the average debt-to-income ratio for each risk category?

In [150]:
df.groupby("Risk_Category")["Debt_to_Income_Ratio"].mean()

Risk_Category
High      0.762786
Low       0.331235
Medium    0.627882
Name: Debt_to_Income_Ratio, dtype: float64

32. How do average credit score, annual income and loan amount vary across risk

In [153]:
df.groupby("Risk_Category")[["Credit_Score","Annual_Income_INR","Loan_Amount_INR"]].mean()

               Credit_Score  Annual_Income_INR  Loan_Amount_INR
Risk_Category
High             637.274127       9.624176e+05     3.113069e+06
Low              718.371958       1.698481e+06     9.259717e+05
Medium           668.628467       1.263373e+06     1.832867e+06

33. How many high-risk loan accounts are present in each city?

In [154]:
df[df["Risk_Category"]=="High"]["City"].value_counts()

City
Pune            38
Mumbai          31
Bengaluru       15
Delhi           14
Nashik          14
Nagpur          13
Chennai         12
Lucknow         11
Thane           10
Indore           9
Surat            7
Kolkata          7
Ahmedabad        7
Jaipur           6
Hyderabad        4
Unknown City     4
Name: count, dtype: int64

34. Which loan type has the highest number of defaulted accounts?

In [ ]:
defaulted = df[df["Default_Flag"] == "Yes"]
defaulted["Loan_Type"].value_counts()

35. What is the default percentage for each loan type?

36. Which employment category has the highest default percentage?

37. Which loan type has the highest number of late or missed-payment accounts?

38. What are the top ten customers by total sanctioned loan amount?

39. What are the top ten loan accounts by outstanding balance?